### ISSUE TITLE
De laatste zin van de samenvatting grammaticaal onjuist en loopt niet

### ISSUE THREAD

**Issue by JosVanderArend** [Logius-standaarden/BOMOS-Stelsels#6]
### Soort

- [X] Tekstuele fout
- [ ] Verbetersuggestie
- [ ] Onduidelijke tekst

### Omschrijving

Deze zin "Een voorbeelden uit de praktijk dat buiten scope van het BOMOS Fundament valt maar waarbinnen BOMOS wel toegepast kan worden." is grammaticaal onjuist en de zin loopt niet.

### Naam

Jos van der Arend

### Email

j.vanderarend@kennisnet.nl

### Organisatie

Kennisnet

**Comment by edwinwisse** [comment]
Aangepast in aparte branch. Ik heb de auteur van dit stuk om feedback gevraagd.
